import type { Locale, PublicProfile, StoryScene } from "./index";

// Editorial starting copy for Osamah's primary profile. The public API uses
// osama-flutter, while the earlier local profile used osamah.
// A published, edited story always replaces this source.
export function isOsamahProfileSlug(slug: string): boolean {
  return slug === "osamah" || slug === "osama-flutter";
}

export const defaultStoryScenes: Record<Locale, StoryScene[]> = {
  ar: [
    { key: "intro", stage: "intro", title: "من التطبيق إلى الخدمة التي تدعمه.", body: "أطوّر تطبيقات Flutter بخبرة متقدمة، وأشارك مع فرق الباك إند في بناء خدمات .NET وبيانات PostgreSQL. هنا ترى كيف يرتبط ما يستخدمه الناس بما يجري خلفه.", detail: "هذه رحلة عبر مجالات عملي. كل مشروع مذكور قصة مستقلة، ومساهمتي في خدمات Bas الخلفية كانت ضمن فريق." },
    { key: "action", stage: "action", title: "الطلب يبدأ هنا", body: "لمسة واحدة تبدو بسيطة. خلفها، ينظّم التطبيق ما أُدخل ويخبر المستخدم بما يحدث قبل أن ينتقل الطلب إلى الخطوة التالية.", detail: "هذا إجراء توضيحي، وليس شاشة أو عملية من منتج منشور. الهدف شرح مسار الطلب من الواجهة إلى النتيجة." },
    { key: "layers", stage: "layers", title: "ما يظهر، وما يُحفظ", body: "الواجهة، وحالة العملية، والبيانات المحلية: لكل منها مسؤولية واضحة حتى يبقى التطبيق مفهومًا وقادرًا على المتابعة.", detail: "في أعمال الهاتف أتعامل مع الواجهات، إدارة الحالة، تكاملات المنصة، البيانات المحلية وواجهات REST. يختلف التنفيذ الفعلي بين المنتجات." },
    { key: "offline", stage: "offline", title: "إذا انقطع الاتصال، لا تختفي الخطوة", body: "في Social Remittances دعمت عمليات صرف تعمل مع الاتصال وبدونه؛ تحفظ البيانات محليًا ثم تُزامن في الخلفية عند توفر الاتصال.", detail: "الموثق في المشروع: تخزين SQLite المحلي، التقاط المستندات، وAndroid WorkManager لمزامنة يمكن أن تستمر بعد إغلاق التطبيق. الرسم مبسّط ولا يصف بروتوكول المزامنة أو ضمانات التسليم الدقيقة.", projectSlug: "social-remittances" },
    { key: "backend", stage: "backend", title: "خلف واجهة الدفع في Bas", body: "في Bas شاركت مع فريق الباك إند في خدمات .NET: بدء الدفع، متابعة حالته، وإرجاع الخيارات والحقول التي تعرضها واجهة Flutter Web.", detail: "العمل الخلفي في Bas كان مساهمة ضمن فريق وشمل أيضًا تكاملات البنوك والمحافظ المحلية. الرسم يشرح مسار الطلب بصورة مبسطة، ولا يعرض البنية الفعلية للخدمة.", projectSlug: "bas-payment-gateway" },
    { key: "backend-decisions", stage: "backend-focus", title: "البيانات والتحقق قبل النتيجة", body: "شاركت مع الفريق في عمل PostgreSQL وEF Core والتحقق من المدخلات والاختبارات ومعالجة مشكلات الإنتاج، حتى تعود نتيجة الدفع واضحة للتطبيق.", detail: "هذه أمثلة من نطاق مساهمتي مع فريق Bas، وليست ادعاءً بأنني نفذت خدمة الدفع أو معماريتها بمفردي. الرسم توضيحي ولا يمثّل مخطط قاعدة البيانات الفعلي.", visualLabel: "مساهمة في Backend ضمن فريق Bas", projectSlug: "bas-payment-gateway" },
    { key: "integration", stage: "integration", title: "جانب آخر من Bas", body: "في المشروع نفسه بنيت واجهات دفع بـFlutter Web وتكاملات Kotlin Multiplatform، مع جسر يتيح استخدامها من تطبيقات Flutter.", detail: "تكتمل هنا صورة Bas من جهة العميل. يشمل العمل مكتبة KMP لتكاملات Kotlin وJava وSwift وجسر Flutter. الرسم لا يصوّر بنية خدمة الدفع الخلفية.", projectSlug: "bas-payment-gateway" },
    { key: "operations", stage: "operations", title: "من الواقع إلى مسار واضح", body: "في Idris حوّلت خطوات تشغيلية واقعية إلى متطلبات وتدفقات مفهومة داخل التطبيق، بالتعاون مع مهندسي الخدمات الخلفية.", detail: "ساهمت بصورة كبيرة في تشكيل سير العمل التشغيلي وهندسة جانب التطبيق، وشاركت الفريق في أعمال .NET وPostgreSQL دون أن أنسب تصميم خدمات المنصة إليّ بمفردي.", projectSlug: "idris-platform" },
    { key: "return", stage: "return", title: "ثم تعود النتيجة إليك", body: "يبدأ المسار من إنسان يستخدم التطبيق، ويمر بمنطق الخدمة الخلفية، ثم يعود إليه بنتيجة واضحة. هذا هو الرابط الذي أحب بناءه.", detail: "تصفح الأعمال لمعرفة حدود دوري في كل مشروع، أو حمّل السيرة التقليدية للتفاصيل المهنية." }
  ],
  en: [
    { key: "intro", stage: "intro", title: "From the app to the service behind it.", body: "I bring senior Flutter experience and contribute with backend teams to .NET services and PostgreSQL data. This is how the experience people use connects to the work behind it.", detail: "This journey covers separate projects. My backend work on Bas was a team contribution." },
    { key: "action", stage: "action", title: "It starts with a request", body: "One tap looks simple. Behind it, the app organizes the input and shows what is happening before the request moves on.", detail: "The request is illustrative. It is not a screen or transaction from a published product." },
    { key: "layers", stage: "layers", title: "What appears, what stays", body: "The interface, the state of the action, and local data each have a clear job. Together they keep the app understandable and ready to continue.", detail: "My mobile work spans interfaces, state, platform integrations, local data, and REST APIs. The exact implementation differs across products." },
    { key: "offline", stage: "offline", title: "When the signal disappears", body: "For Social Remittances, I supported disbursement workflows online and offline. Local records could be synchronized in the background when connectivity returned.", detail: "The published project documents SQLite storage, document capture, and Android WorkManager synchronization that could continue after the app closed. This diagram does not claim a particular sync protocol or delivery guarantee.", projectSlug: "social-remittances" },
    { key: "backend", stage: "backend", title: "Behind a Bas payment", body: "For Bas, I worked with the backend team on .NET services for starting payments, checking status, and returning the options and fields shown in the Flutter Web interface.", detail: "The Bas backend contribution also included local bank and wallet integrations. This drawing simplifies the request flow; it does not show the service's actual architecture.", projectSlug: "bas-payment-gateway" },
    { key: "backend-decisions", stage: "backend-focus", title: "Data and checks before a result", body: "With the team, I contributed to PostgreSQL and EF Core data work, input validation, testing, and production troubleshooting so the app could present a clear payment result.", detail: "These are team contributions to Bas, not a claim that I built its payment service or architecture alone. The drawing is illustrative, not the actual database design.", visualLabel: "Bas backend team contribution", projectSlug: "bas-payment-gateway" },
    { key: "integration", stage: "integration", title: "The other side of Bas", body: "In the same project, I built Flutter Web payment interfaces and Kotlin Multiplatform integrations, including a bridge for Flutter clients.", detail: "This completes the client side of the Bas story: a KMP library for Kotlin, Java, and Swift integrations and a Flutter channel bridge. The drawing does not represent Bas's backend architecture.", projectSlug: "bas-payment-gateway" },
    { key: "operations", stage: "operations", title: "From real work to usable flows", body: "At Idris, I translated operational steps into app requirements and flows, working with backend engineers on system analysis.", detail: "I contributed substantially to shaping operational workflows and application engineering, and joined team work on .NET and PostgreSQL without claiming sole ownership of its backend services.", projectSlug: "idris-platform" },
    { key: "return", stage: "return", title: "The result comes back to you", body: "The journey begins with someone using an app, passes through service logic, and returns with a clear result. That is the connection I enjoy building.", detail: "Explore individual projects for the exact scope of my role, or download the conventional resume." }
  ]
};

export function storyFor(profile: PublicProfile, isDefault: boolean): StoryScene[] | undefined {
  if (profile.story?.length) return profile.story;
  if (isDefault && isOsamahProfileSlug(profile.slug) && !profile.demo) return defaultStoryScenes[profile.locale];
  return undefined;
}
