import type { Locale, PublicProfile, StoryScene } from "./index";

// Editorial starting copy for the existing primary profile. A published, edited story
// always replaces this source; other profiles keep the regular profile layout.
export const defaultStoryScenes: Record<Locale, StoryScene[]> = {
  ar: [
    { key: "intro", stage: "intro", title: "أبني التطبيق. وأبني ما وراءه.", body: "من واجهة يلمسها الناس إلى خدمة تستقبل الطلب وتعيد نتيجة واضحة. أعمل على طرفَي الرحلة، وأهتم بأن يفهم كل طرف الآخر.", detail: "هذه رحلة تفسيرية عبر مجالات عملي. كل مشروع مذكور يُعرض بوصفه قصة مستقلة، وليس أجزاءً من منتج واحد." },
    { key: "action", stage: "action", title: "الطلب يبدأ هنا", body: "لمسة واحدة تبدو بسيطة. خلفها، ينظّم التطبيق ما أُدخل ويخبر المستخدم بما يحدث قبل أن ينتقل الطلب إلى الخطوة التالية.", detail: "هذا إجراء توضيحي، وليس شاشة أو عملية من منتج منشور. الهدف شرح مسار الطلب من الواجهة إلى النتيجة." },
    { key: "layers", stage: "layers", title: "ما يظهر، وما يُحفظ", body: "الواجهة، وحالة العملية، والبيانات المحلية: لكل منها مسؤولية واضحة حتى يبقى التطبيق مفهومًا وقادرًا على المتابعة.", detail: "في أعمال الهاتف أتعامل مع الواجهات، إدارة الحالة، تكاملات المنصة، البيانات المحلية وواجهات REST. يختلف التنفيذ الفعلي بين المنتجات." },
    { key: "offline", stage: "offline", title: "إذا انقطع الاتصال، لا تختفي الخطوة", body: "في Social Remittances دعمت عمليات صرف تعمل مع الاتصال وبدونه؛ تحفظ البيانات محليًا ثم تُزامن في الخلفية عند توفر الاتصال.", detail: "الموثق في المشروع: تخزين SQLite المحلي، التقاط المستندات، وAndroid WorkManager لمزامنة يمكن أن تستمر بعد إغلاق التطبيق. الرسم مبسّط ولا يصف بروتوكول المزامنة أو ضمانات التسليم الدقيقة.", projectSlug: "social-remittances" },
    { key: "backend", stage: "backend", title: "هنا يبدأ عمل الخدمة", body: "أطوّر أيضًا الجانب الخلفي: استقبال الطلب، تنظيم منطقه وبياناته، ثم إرجاع استجابة يمكن للتطبيق أن يشرحها بوضوح.", detail: "هذا مخطط تفسيري لمجال عملي في الخدمات الخلفية، وليس وصفًا لمعمارية منتج منشور أو ادعاءً بملكية خدمة محددة." },
    { key: "backend-decisions", stage: "backend-focus", title: "القرار قبل الاستجابة", body: "في الخدمة الخلفية أرى سلسلة قرارات، لا صندوقًا مغلقًا: تحقق من المدخلات، قواعد للعمل، وصول إلى البيانات، ثم نتيجة يفهمها التطبيق.", detail: "الرسم يوضح مسؤوليات عامة في Backend. سنستبدله لاحقًا بمثال موثق يحدد المشروع، دوري فيه، التقنية المستخدمة، القرار الهندسي، وحدود هذا القرار.", visualLabel: "مسؤوليات الخدمة الخلفية — مثال توضيحي" },
    { key: "integration", stage: "integration", title: "قصة أخرى: Bas", body: "في Bas بنيت واجهات دفع بـFlutter Web وتكاملات Kotlin Multiplatform، مع جسر يتيح استخدامها من تطبيقات Flutter.", detail: "هذا انتقال إلى مشروع مستقل. المحتوى المنشور يوثق مكتبة KMP لتكاملات Kotlin وJava وSwift وجسر Flutter. لا يصوّر الرسم بنية خدمة المدفوعات الخلفية.", projectSlug: "bas-payment-gateway" },
    { key: "operations", stage: "operations", title: "من الواقع إلى مسار واضح", body: "في Idris أحوّل خطوات تشغيلية واقعية إلى متطلبات وتدفقات مفهومة داخل التطبيق، بالتعاون مع مهندسي الخدمات الخلفية.", detail: "الموثق هنا هو هندسة جانب التطبيق وتحليل الأنظمة مع فريق الـBackend؛ لا أنسب إلى نفسي تصميم خدمات Idris الخلفية.", projectSlug: "idris-platform" },
    { key: "return", stage: "return", title: "ثم تعود النتيجة إليك", body: "يبدأ المسار من إنسان يستخدم التطبيق، ويمر بمنطق الخدمة الخلفية، ثم يعود إليه بنتيجة واضحة. هذا هو الرابط الذي أحب بناءه.", detail: "تصفح الأعمال لمعرفة حدود دوري في كل مشروع، أو حمّل السيرة التقليدية للتفاصيل المهنية." }
  ],
  en: [
    { key: "intro", stage: "intro", title: "I build the app. And what powers it.", body: "From the interface people touch to the service that receives a request and returns a clear result. I work on both sides of that journey and how they fit together.", detail: "This is an explanatory journey through my work. Each named project is a separate story, not a piece of one combined product." },
    { key: "action", stage: "action", title: "It starts with a request", body: "One tap looks simple. Behind it, the app organizes the input and shows what is happening before the request moves on.", detail: "The request is illustrative. It is not a screen or transaction from a published product." },
    { key: "layers", stage: "layers", title: "What appears, what stays", body: "The interface, the state of the action, and local data each have a clear job. Together they keep the app understandable and ready to continue.", detail: "My mobile work spans interfaces, state, platform integrations, local data, and REST APIs. The exact implementation differs across products." },
    { key: "offline", stage: "offline", title: "When the signal disappears", body: "For Social Remittances, I supported disbursement workflows online and offline. Local records could be synchronized in the background when connectivity returned.", detail: "The published project documents SQLite storage, document capture, and Android WorkManager synchronization that could continue after the app closed. This diagram does not claim a particular sync protocol or delivery guarantee.", projectSlug: "social-remittances" },
    { key: "backend", stage: "backend", title: "The service takes over", body: "I also build backend services: receiving a request, handling its logic and data, then returning a response the app can explain clearly.", detail: "This is an explanatory model of my backend work, not a diagram of a published product or a claim of ownership of a particular service." },
    { key: "backend-decisions", stage: "backend-focus", title: "Decisions before responses", body: "A service is a series of decisions: validate the input, apply rules, access data, and shape a result the app can use.", detail: "The drawing shows general backend responsibilities. A documented example can later name the project, my role, the technology, an engineering decision, and its limits.", visualLabel: "Backend responsibilities — illustrative model" },
    { key: "integration", stage: "integration", title: "Another story: Bas", body: "For Bas, I built payment interfaces with Flutter Web and Kotlin Multiplatform integrations, including a bridge for Flutter clients.", detail: "This is a separate project. The published record covers a KMP library for Kotlin, Java, and Swift integrations and a Flutter channel bridge. The drawing does not represent Bas's backend architecture.", projectSlug: "bas-payment-gateway" },
    { key: "operations", stage: "operations", title: "From real work to usable flows", body: "At Idris, I translate operational steps into app requirements and flows, working with backend engineers on system analysis.", detail: "The documented contribution is application engineering and collaboration with backend engineers. It does not assign ownership of Idris backend services to me.", projectSlug: "idris-platform" },
    { key: "return", stage: "return", title: "The result comes back to you", body: "The journey begins with someone using an app, passes through service logic, and returns with a clear result. That is the connection I enjoy building.", detail: "Explore individual projects for the exact scope of my role, or download the conventional resume." }
  ]
};

export function storyFor(profile: PublicProfile, isDefault: boolean): StoryScene[] | undefined {
  if (profile.story?.length) return profile.story;
  if (isDefault && profile.slug === "osamah" && !profile.demo) return defaultStoryScenes[profile.locale];
  return undefined;
}
